MelanieCouronne/MamieExpress

app/controllers/users_controller.rb, app/models/user.rb, db/migrate/20211116100457_create_users.rb, db/migrate/20211116101917_change_name_adresse_to_users.rb, db/schema.rb, test/controllers/users_controller_test.rb, test/models/user_test.rb
Can you check the model users and controller ?
=> le model Users + controller sont crees

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/routes.rb, db/migrate/20211116112530_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Thanks to check the new set of user model and merge if ok
﻿
=> Set model User with devise and migrate

Gemfile.lock, app/controllers/grannies_controller.rb, app/models/granny.rb, app/models/user.rb, db/migrate/20211116115952_create_grannies.rb, db/schema.rb, test/controllers/grannies_controller_test.rb, test/models/granny_test.rb
Can you check my models / controllers for grannies?
=> Create model grannies

Gemfile.lock, app/views/layouts/application.html.erb, config/environments/development.rb
Hello! New setup for devise! Could you check please!
=> Set device

db/migrate/20211116151529_add_arrival_location_to_travels.rb, db/migrate/20211116151705_add_departure_location_to_travels.rb, db/schema.rb
les colonnes arrival location + departure location sont add dans la table travels﻿
=> columns locations add in travels table

app/controllers/application_controller.rb, app/controllers/travels_controller.rb, app/models/travel.rb, app/policies/application_policy.rb, app/policies/travel_policy.rb, app/views/travels/_form.html.erb, app/views/travels/new.html.erb, test/policies/travel_policy_test.rb
Add autorization to new and create
+ first design for the form! 🚀
=> Add create action to travels

app/views/travels/index.html.erb, db/migrate/20211117094434_change_date_hour_type_to_date_format.rb, db/schema.rb
I've change the type in travels (departure_date | arrival_date / hour) => datetime
+ number_passenger to integer.
=> change type to date + integer in travels_table

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/travels/_form.html.erb
Move navbar to application.hmtl.erb
Add Font Awesome +
Change color
Remove dead links and user picture
=> Add link new to navbar

Gemfile.lock, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_footer.html.erb, db/schema.rb
=> Add links and picto to footer

Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/travels/_form.scss, app/views/travels/_form.html.erb
=> New background

Gemfile.lock, app/assets/stylesheets/travels/_show.scss, app/controllers/travels_controller.rb, app/models/travel.rb, app/views/travels/_info_window.html.erb, app/views/travels/show.html.erb, db/migrate/20211117122413_add_arrival_latitude_to_travels.rb, db/migrate/20211117122442_add_arrival_longitude_to_travels.rb, db/schema.rb
- pull de la request sur la map
- finalisation map
- map is working
- map is working
=> add longlat map

app/views/travels/_form.html.erb, app/views/travels/show.html.erb
Change form date and hour, en vous remerciant
=> Change form date and hour

app/models/travel.rb
Quick changed of validations on model Travel
=> Removed validation for hour

app/controllers/travels_controller.rb, app/views/travels/edit.html.erb
=> Added edit action and form

app/controllers/travels_controller.rb
Added destroy action to travels controller
=> Added destroy action to travels controller

db/migrate/20211117172103_remove_dates_from_travels.rb, db/migrate/20211117172602_add_date_to_travels.rb, db/schema.rb
Removed date and hour from travels controller
Added datime to travels controller
=> Remove columns

app/assets/stylesheets/components/_cards-travel.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/travels/_index.scss, app/views/travels/index.html.erb
check the update of index#travel with the departure_date update
=> index a jour avec les colonnes dates/travels

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, config/routes.rb
Set home path on logo and "Rechercher un trajet"
Travels index are not anymore the home page >>> it's pages#home
Hide "Rechercher un trajet" when we are on the home page
Add "Mes trajets" to dropdown when connected
Add "Connexion" and "Inscription" to dropdown when not logged
=> Navbar dropdown

app/assets/stylesheets/travels/_form.scss, app/views/travels/_form.html.erb
=> Changed time into datetime

app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
=> Fixbug on current_path

app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js
=> Added autocomplete to form inputs adress

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb
=> Created container for user new and edit views

Gemfile.lock
=> commit to fixed

Gemfile.lock, app/assets/stylesheets/travels/_form.scss, app/assets/stylesheets/travels/_show.scss, app/assets/stylesheets/users/_profile.scss, app/views/travels/show.html.erb, app/views/users/profile.html.erb
- recup site
- fix des footer et du profile
=> profile cleaning

Gemfile.lock, app/views/pages/home.html.erb, app/views/travels/index.html.erb, app/views/travels/show.html.erb
=> text card  fixed

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_cards-travel.scss, app/views/travels/index.html.erb
J'ai arrondi les avatars + rapproché les boutons des cards
=> le front de l'index est amelioré

Gemfile.lock, app/assets/stylesheets/users/_profile.scss, app/views/users/profile.html.erb
- pull master
- new form frenchy
=> fix profile

Gemfile.lock, app/controllers/travels_controller.rb, app/models/travel.rb
=> Search global
